services:
  js-backend:
    build:
      context: ./backend
      dockerfile: ../backendDockerfile
    container_name: js-backend
    restart: unless-stopped
    init: true
    env_file: ./backend/.env
    ports:
      - "4000:4000"  # Exposed by backend Dockerfile
    depends_on:
      - postgres
    networks:
      - polp-net

  js-frontend:
    build:
      context: ./frontend
      dockerfile: ../frontendDockerfile
    container_name: js-frontend
    restart: unless-stopped
    init: true
    env_file: ./frontend/.env
    ports:
      - "4173:4173"  # Exposed by frontend Dockerfile
    depends_on:
      - js-backend
    networks:
      - polp-net

  postgres:
    image: postgres:latest
    container_name: polp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: polpo
      POSTGRES_DB: polp_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polp"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - polp-net
    # Uncomment the following lines to persist database data
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

networks:
  polp-net:
    driver: bridge

# Uncomment the following if you want to persist Postgres data
#volumes:
#  postgres-data:
#    driver: local
